CREATE TABLE IF NOT EXISTS contractors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name VARCHAR(255),
    normalized_business_name VARCHAR(255),
    person_name VARCHAR(255),
    normalized_person_name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_contractors_business ON contractors (normalized_business_name);
CREATE INDEX IF NOT EXISTS idx_contractors_person ON contractors (normalized_person_name);

CREATE TABLE IF NOT EXISTS credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contractor_id BIGINT NOT NULL,
    credential_number VARCHAR(255),
    credential_type VARCHAR(255) NOT NULL,
    credential_kind VARCHAR(20) NOT NULL CHECK (credential_kind IN ('LICENSE', 'REGISTRATION', 'RECORD')),
    issuing_authority VARCHAR(255) NOT NULL,
    jurisdiction VARCHAR(255),
    status VARCHAR(100),
    expiration_date DATE,
    source_url TEXT,
    source_record_number VARCHAR(255),
    last_verified DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_credentials_contractor FOREIGN KEY (contractor_id)
        REFERENCES contractors(id) ON DELETE CASCADE,
    CONSTRAINT uq_credential_authority_number UNIQUE (issuing_authority, credential_number)
);

CREATE INDEX IF NOT EXISTS idx_credentials_type ON credentials (credential_type);
CREATE INDEX IF NOT EXISTS idx_credentials_authority ON credentials (issuing_authority);

CREATE TABLE IF NOT EXISTS import_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(255) NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP NULL,
    rows_seen INT NOT NULL DEFAULT 0,
    rows_inserted INT NOT NULL DEFAULT 0,
    rows_updated INT NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS review_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incoming_json JSONB NOT NULL,
    candidate_contractor_id BIGINT,
    reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL,
    resolution TEXT,
    CONSTRAINT fk_review_contractor FOREIGN KEY (candidate_contractor_id)
        REFERENCES contractors(id) ON DELETE SET NULL
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS contractors_set_updated_at ON contractors;
CREATE TRIGGER contractors_set_updated_at
BEFORE UPDATE ON contractors
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS credentials_set_updated_at ON credentials;
CREATE TRIGGER credentials_set_updated_at
BEFORE UPDATE ON credentials
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
